//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace memo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class slowko
    {
        [Required]
        [Display(Name = "Wersja angielska")]
        public string eng { get; set; }
        [Required]
        [Display(Name = "Wersja polska")]
        public string pl { get; set; }
    }
}
