//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace memo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class statystykaUzytkownika
    {
        public string nazwa { get; set; }
        public int dobreOdpowiedzi { get; set; }
        public int zleOdpowiedzi { get; set; }
    
        public virtual uzytkownik uzytkownik { get; set; }
    }
}
