//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace memo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uzytkownik
    {
        public string nazwa { get; set; }
        public string haslo { get; set; }
        public int rola { get; set; }
        public int ustawienia { get; set; }
    
        public virtual rola rola1 { get; set; }
        public virtual statystykaUzytkownika statystykaUzytkownika { get; set; }
        public virtual ustawieniaZagadki ustawieniaZagadki { get; set; }
    }
}
